### ISSUE TITLE
Add Patch RGB Image to Predicted v Ground Truth Plots

### ISSUE THREAD

**Issue by Pale-Blue-Dot-97** [Pale-Blue-Dot-97/Minerva#10]
### Context 

Data visualisation of predicted versus ground truth labels from model testing would be greatly enhanced by the ability to compare labels to actual RGB imagery of patch and the coordinates.

### Tasks

- [x] Fix bug from Issue #9 
- [x] Copy across logic on patch RGB imagery plotting
- [x] Re-engineer copied code for use as a third subplot in predicted v ground truth plots
- [x] Copy across logic on image coordinates
- [x] Re-engineer into this plotting functionality
- [ ] Possibly generalise this additional functionality across multiple plotting methods in `visutils.py` module
