### ISSUE TITLE
Add a Simple CNN Model

### ISSUE THREAD

**Issue by Pale-Blue-Dot-97** [Pale-Blue-Dot-97/Minerva#2]
### Task
The main task of the Minerva CNN project is to add a simple CNN model to `models.py`.  

### Steps

- [x] Create new `class` in `models.py`
- [x] Copy across logic from `MLP`
- [x] Re-engineer to a CNN model from `pytorch`
- [x] Create new top-level `python` script to create CNN model and fit via `Trainer`
